name: Node.js Package

env:
  GH_PAT: ${{ secrets.GH_PAT }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
        registry-url: 'https://registry.npmjs.org'
    - run: npm ci
      env:
        CI: true
    - name: Versioning and Publishing
      run: |
        git config user.name "Luke Blauvelt"
        git config user.email "lukeblauvelt@gmail.com"
        npm version patch -m "Upgrade to %s"
        git remote set-url origin https://x-access-token:${GH_PAT}@github.com/SwiftSignIn/SwiftAuthSDK.git
        git push --tags
        npm publish
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
