name: Node.js Package

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
        registry-url: 'https://registry.npmjs.org'
    - run: npm ci
      env:
        CI: true
    - run: npm install standard-version -g
    - run: standard-version
    - run: git push --follow-tags origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: npm publish
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
